### DISCUSSION TITLE
Support anaconda-project.yml

### DISCUSSION THREAD

**Discussion by AlbertDeFusco** [brettcannon/WWBD#35] [Ideas]
Similar to #5 you might consider supporting [Anaconda Project](https://anaconda-project.readthedocs.io/en/latest/). Anaconda Project (and its eventual successor [conda-project](https://github.com/conda-incubator/conda-project)) extends the concepts of environment.yml to include runable commands, environment variables, data downloads, and multiple conda environments within a single project/directory. An important difference is that all Conda environments defined through the anaconda-project.yml file are installed local to the project in the `./envs` folder. The Python extension already searches for a `./envs` directory and provides conda environments found there as recommended in the environment discovery.

It would be really cool for either the future Python extension or an extension specific to Anaconda Project that activates only when `anaconda-project.yml` is found to offer to run `anaconda-project prepare` on the terminal which will install the environment[s] defined in the yaml file if they are not already present and the sets active environment appropriately, ignoring the global conda environments.

**Comment by brettcannon** [comment]
[Docs for `anaconda-project prepare`](https://anaconda-project.readthedocs.io/en/latest/user-guide/tasks/prepare-project.html).

> all Conda environments defined through the anaconda-project.yml file are installed local to the project in the `./envs` folder.

Can there be more than one environment? I ask because if there can be then it becomes of a question of how does one choose which environment to select? I'm assuming most people only have one, but if they can have more than one is there any hint as to which one the user most likely wants?

**Comment by AlbertDeFusco** [comment]
Anaconda Project has its own procedure for determining the "default" of something and I can add a cli command to return the name or path to the "default" environment, like `anaconda-project default-env-prefix`. The CLI command `anaconda-project list-env-specs` returns names of defined envs. Perhaps if more than one env is found only those could be shown in the env picker by default.

When Anaconda Project is faced with a choice between environments (`anaconda-project prepare`) and commands (`anaconda-project run`) because the user did not specify which environment to prepare or which command to run it will look for one named "default" and use that. If no env or command is named "default" it will use the first one to appear in the `anaconda-project.yml` file (not alphabetical order)

I will go into some extreme detail below for how Anaconda Project determines the default behavior.

## Minimal project yaml file

```yaml
name: example-project

dependencies:
  - python=3.8
  - flask
 
channels:
  - defaults
 
commands:
  server:
    unix: python app.py
```

In this scenario `anaconda-project prepare` creates a default environment with the listed dependencies at `./envs/default`. This minimal file is equivalent to

```yaml
name: example-project

dependencies:
  - python=3.8
  - flask

channels:
  - defaults

commands:
  server:
    unix: python app.py
    env_spec: default

env_specs:
  default:
    dependencies: []
    channels: []
```

Where the keys in `env_specs` are named Conda environments. Here I'm using the name `default`, which is what anaconda-project will fill in if `env_specs` is not provided. Notice also that the "server" command now explicitly states that it runs in the "default" env, again anaconda-project will assume that if not provided.

## Multiple environments

It is somewhat common to have multiple environments, for example an env for development and testing separate from what is needed to run the application. Here I'm going to keep the default environment and add a second one in this case I must write out `env_specs`

```yaml
name: example-project

dependencies:
  - python=3.8
  - flask

channels:
  - defaults

commands:
  server:
    unix: python app.py
  test:
    unix: pytest -xvv
   env_spec: develop

env_specs:
  develop:
    dependencies:
      - pytest
  default:
    dependencies: []
    channels: []
```



Because there is an env_spec named "default" `anaconda-project prepare` will install that even though it is listed secondly in the file. The user must ask for the "develop" env in order to install it `anaconda-project prepare --env-spec develop`.

Notice that there is no command named "default" so `anaconda-project run` will execute the "server" command. The server command does not specify an env_spec so anaconda-project follows the standard rule and assumes that the "default env" will be used.

When the user explicitly executes the test (`anaconda-project run test`) command anaconda-project will ensure that the required env (`develop`) has already been prepared.
